package com.jerry.bookcloud.account.model;

import java.util.Date;

public class UserBookshelf {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bookshelf.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bookshelf.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bookshelf.book_id
     *
     * @mbg.generated
     */
    private String bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bookshelf.last_chapter_id
     *
     * @mbg.generated
     */
    private Integer lastChapterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bookshelf.last_read_time
     *
     * @mbg.generated
     */
    private Long lastReadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bookshelf.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bookshelf.id
     *
     * @return the value of user_bookshelf.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bookshelf.id
     *
     * @param id the value for user_bookshelf.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bookshelf.user_id
     *
     * @return the value of user_bookshelf.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bookshelf.user_id
     *
     * @param userId the value for user_bookshelf.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bookshelf.book_id
     *
     * @return the value of user_bookshelf.book_id
     *
     * @mbg.generated
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bookshelf.book_id
     *
     * @param bookId the value for user_bookshelf.book_id
     *
     * @mbg.generated
     */
    public void setBookId(String bookId) {
        this.bookId = bookId == null ? null : bookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bookshelf.last_chapter_id
     *
     * @return the value of user_bookshelf.last_chapter_id
     *
     * @mbg.generated
     */
    public Integer getLastChapterId() {
        return lastChapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bookshelf.last_chapter_id
     *
     * @param lastChapterId the value for user_bookshelf.last_chapter_id
     *
     * @mbg.generated
     */
    public void setLastChapterId(Integer lastChapterId) {
        this.lastChapterId = lastChapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bookshelf.last_read_time
     *
     * @return the value of user_bookshelf.last_read_time
     *
     * @mbg.generated
     */
    public Long getLastReadTime() {
        return lastReadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bookshelf.last_read_time
     *
     * @param lastReadTime the value for user_bookshelf.last_read_time
     *
     * @mbg.generated
     */
    public void setLastReadTime(Long lastReadTime) {
        this.lastReadTime = lastReadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bookshelf.create_time
     *
     * @return the value of user_bookshelf.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bookshelf.create_time
     *
     * @param createTime the value for user_bookshelf.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}