package com.jerry.bookcloud.homepage.dao;

import com.jerry.bookcloud.common.pojo.index.IndexBooklist;

public interface IndexBooklistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_booklist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_booklist
     *
     * @mbg.generated
     */
    int insert(IndexBooklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_booklist
     *
     * @mbg.generated
     */
    int insertSelective(IndexBooklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_booklist
     *
     * @mbg.generated
     */
    IndexBooklist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_booklist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IndexBooklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_booklist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IndexBooklist record);
}