package com.jerry.bookcloud.homepage.dao;

import com.jerry.bookcloud.common.pojo.index.IndexBanner;

public interface IndexBannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_banner
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_banner
     *
     * @mbg.generated
     */
    int insert(IndexBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_banner
     *
     * @mbg.generated
     */
    int insertSelective(IndexBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_banner
     *
     * @mbg.generated
     */
    IndexBanner selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_banner
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IndexBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_banner
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IndexBanner record);
}