package com.jerry.bookcloud.homepage.dao;

import com.jerry.bookcloud.common.pojo.index.IndexPageConfig;

import java.util.List;

public interface IndexPageConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_page_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_page_config
     *
     * @mbg.generated
     */
    int insert(IndexPageConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_page_config
     *
     * @mbg.generated
     */
    int insertSelective(IndexPageConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_page_config
     *
     * @mbg.generated
     */
    IndexPageConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_page_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IndexPageConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_page_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IndexPageConfig record);

    /***
     * 查询主页配置
     * @param pageType
     * @return
     */
    List<IndexPageConfig> findPageWithResult(Integer pageType);
}